# Generated by Django 4.0.5 on 2022-07-26 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(choices=[('CHICK-LIT', 'Chick-lit'), ('CHILDRENS', 'Childrens'), ('COMICS', 'Comics'), ('CRIME', 'Crime'), ('FANTASY', 'Fantasy'), ('MANGA', 'Manga'), ('MYSTERY', 'Mystery'), ('NONFICTION', 'Nonfiction'), ('ROMANCE', 'Romance'), ('SELFHELP', 'Self Help'), ('SUSPENSE', 'Suspense'), ('THRILLER', 'Thriller'), ('YOUNGADULT', 'Young Adult'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('numberofpages', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
    ]
